"""soc-agent configuration, read from the environment.

No default value for the secrets: an absence must fail the startup, not silently
fall back on a default.
"""

import ipaddress
import os
import sys
from pathlib import Path
from urllib.parse import urlparse


def _required(name: str) -> str:
    val = os.environ.get(name)
    if not val:
        sys.exit(f"Missing environment variable: {name} (see ai/.env.example)")
    return val


# --- Wazuh indexer (source of the alerts) -----------------------------------
#
# We read the indexer rather than being pushed by the manager's integrator: GeoIP
# is applied by an ingest pipeline on the indexer side, so the enrichment exists
# ONLY in that copy. The integrator fires upstream and would see alerts with no
# geolocation.
INDEXER_URL = os.environ.get("INDEXER_URL", "https://127.0.0.1:9200")
INDEXER_USER = os.environ.get("INDEXER_USER", "admin")
INDEXER_PASSWORD = _required("INDEXER_PASSWORD")

# Self-signed certificates generated by the Wazuh stack. Set to true (with
# INDEXER_CA) as soon as the indexer is no longer on the loopback.
INDEXER_VERIFY_TLS = os.environ.get("INDEXER_VERIFY_TLS", "false").lower() == "true"
INDEXER_CA = os.environ.get("INDEXER_CA") or None

# Indices queried for ingestion. An indexer ingest pipeline
# (wazuh/config/wazuh_cluster/alerts-pipeline.json) routes alerts by type: every
# prefix it can produce MUST appear here, otherwise the AI is blind to that
# sensor — silently, since there is neither an error nor a missing alert on the
# Wazuh side, just zero rows in database.
#
# The same trap twice in practice: first wazuh-linux-*/wazuh-web-*, then on
# 2026-07-29 wazuh-yara-* (5 level-12 alerts, one of them a web shell) and
# wazuh-firewall-* (all of Suricata, routed the day before). Hence the exhaustive
# list below, aligned on the pipeline's `index` values.
#
# It no longer has to be maintained by hand: it is the BASE, to which
# `routing.read_indices()` adds the index sets created since (see
# docs/ROUTAGE.md). An index set created without being added here used to be a
# sensor invisible to the AI — it is now a consequence, no longer a vigilance.
INDEXER_ALERT_INDICES = os.environ.get(
    "INDEXER_ALERT_INDICES",
    "wazuh-alerts-*,wazuh-linux-*,wazuh-web-*,wazuh-yara-*,wazuh-firewall-*,"
    "wazuh-proxy-*,wazuh-dns-*,wazuh-vpn-*,wazuh-jellyfin-*,wazuh-windows-*")

# --- soc-agent database -----------------------------------------------------
PG_DSN = os.environ.get(
    "PG_DSN",
    "postgresql://{u}:{p}@127.0.0.1:{port}/{db}".format(
        u=os.environ.get("PGUSER", "socagent"),
        p=_required("PGPASSWORD"),
        port=os.environ.get("PGPORT", "5433"),
        db=os.environ.get("PGDATABASE", "socagent"),
    ),
)

# Cap on the duration of ONE query, applied to every soc-agent connection.
#
# Without it, a query gone wrong ties up its session forever, and everything
# needing a lock on the same tables waits behind — observed on 2026-08-11, a
# migration `ALTER TABLE` stuck behind cycle sessions. A query of this pipeline
# lasting more than five minutes is abnormal anyway: the big batches are split
# (INGEST batch size, UEBA_BATCH).
#
# Deliberately NO idle_in_transaction_session_timeout: the cycle holds its
# advisory lock inside a transaction open for its whole run (see cycle.LOCK).
# Killing it on inactivity would release the lock and allow two concurrent
# cycles — the cure would be worse than the disease.
PG_STATEMENT_TIMEOUT_MS = int(
    os.environ.get("PG_STATEMENT_TIMEOUT_MS", "300000"))


def _with_statement_timeout(dsn: str, ms: int) -> str:
    """Adds `options=-c statement_timeout=<ms>` to the DSN, overwriting nothing.

    Going through the DSN rather than a `SET` after connecting: there is no
    single choke point where every connection is opened (each module does its own
    `psycopg.connect`), so the only place covering them all is the connection
    string itself.
    """
    if ms <= 0 or "options=" in dsn:
        return dsn
    opt = f"-c statement_timeout={ms}"
    if dsn.startswith(("postgresql://", "postgres://")):
        from urllib.parse import quote
        return f"{dsn}{'&' if '?' in dsn else '?'}options={quote(opt)}"
    return f"{dsn} options='{opt}'"


PG_DSN = _with_statement_timeout(PG_DSN, PG_STATEMENT_TIMEOUT_MS)

# --- Filtering --------------------------------------------------------------
#
# Minimum Wazuh level to OPEN an incident (seed). 12 = the HIGH threshold of the
# 0-15 scale (12-14 high, 15 critical): an IRIS case plus AI analysis only fire
# on a HIGH/CRITICAL alert. Below that, an alert never opens an incident but can
# be ATTACHED to an already confirmed one to enrich it (see ATTACH_MIN_LEVEL) —
# the analysis sees everything, opening stays reserved for the strong signal.
MIN_LEVEL = int(os.environ.get("MIN_LEVEL", "12"))

# --- VirusTotal filter for legitimate executables ----------------------------
#
# Before correlation, an alert carrying an executable HASH (Sysmon, FIM, VT
# integration) is checked against the VirusTotal reputation of that hash. A
# binary judged LEGITIMATE (no positive engine, hash known to VT) makes the alert
# suppressed: a clean exe must not weigh in a case, nor open one when it is
# alone. A deterministic filter (not the LLM); full audit trail
# (suppress_reason plus the VT cache).
#
# Reuses the key of Wazuh's VirusTotal integration. Without a key the filter is
# inactive (no call, nothing suppressed).
VT_API_KEY = os.environ.get("VT_API_KEY", "").strip()
VT_URL = os.environ.get("VT_URL", "https://www.virustotal.com/api/v3")
# Only checks against VT the executables of alerts at least at this level: those
# that could seed or join a case. Below it, the noise filter is enough.
VT_EXE_MIN_LEVEL = int(os.environ.get("VT_EXE_MIN_LEVEL", "7"))
# A VT verdict is recomputed past this age (an unknown hash can turn malicious).
# Under that TTL we read the cache.
VT_CACHE_TTL_DAYS = int(os.environ.get("VT_CACHE_TTL_DAYS", "14"))
# Cap on VT network calls per pass (public API: 4 req/min, 500/day). The cache
# absorbs the rest; the unresolved ones are retried on the next cycle.
VT_MAX_LOOKUPS = int(os.environ.get("VT_MAX_LOOKUPS", "4"))
# Minimum number of engines having analysed the hash to believe a "clean"
# verdict (a barely known hash proves no legitimacy). Below it: 'unknown', we do
# not suppress (when in doubt we keep the alert).
VT_MIN_ENGINES = int(os.environ.get("VT_MIN_ENGINES", "5"))
# Never suppress an executable located in a system directory: a signed System32
# binary (powershell.exe, certutil.exe...) is clean to VT but can be abused
# (LOLBin) — detection there is BEHAVIOURAL, not file-based. We only filter the
# executables DROPPED elsewhere (temp, profiles, /tmp, /home...).
VT_DIRS_SYSTEM = tuple(d.lower() for d in os.environ.get(
    "VT_DIRS_SYSTEM",
    r"c:\windows,c:\program files,c:\program files (x86),"
    "/usr/bin,/usr/sbin,/bin,/sbin,/usr/lib,/lib").split(","))

# Scope enrichment: once an incident is FORMED by a seed (>= MIN_LEVEL), we
# attach to it EVERY alert of the same agent within its window from this level
# up. Lowered to 3 to capture command auditing (rule 80792, level 3): that is
# where enumeration and exploitation live (find SUID, chmod, cat /etc/shadow,
# useradd...). The goal is to reconstruct EVERYTHING the attacker did on the
# compromised machine, not only the peaks. These alerts NEVER create an incident
# on their own (too frequent): they only complete an already confirmed one. 0
# disables enrichment.
ATTACH_MIN_LEVEL = int(os.environ.get("ATTACH_MIN_LEVEL", "3"))

# Level below which we do not even ingest. 0 = store everything, which gives the
# complete statistics; raise it to MIN_LEVEL once the measurement is done.
INGEST_MIN_LEVEL = int(os.environ.get("INGEST_MIN_LEVEL", "0"))

# --- Catching up with late-indexed alerts -----------------------------------
#
# The ingestion cursor advances on `@timestamp`, the date of the EVENT, not of
# its indexing. Any alert becoming visible to search AFTER the cursor has passed
# its timestamp is skipped for good. Two scales of lateness, two answers.
#
# 1. Indexing skew (seconds to minutes): agent -> manager -> indexer transit plus
#    the index refresh. We resume ingestion slightly before the recorded
#    position. The overlap is free, the insert being idempotent (ON CONFLICT DO
#    NOTHING on the native Wazuh id).
INGEST_LOOKBACK_MINUTES = int(os.environ.get("INGEST_LOOKBACK_MINUTES", "15"))

# 2. Agent replay (hours to days): an agent cut off from the manager buffers its
#    logs and replays them on reconnection WITH their original timestamps. The
#    lookback above does not go far enough. Hence a periodic, complete sweep of
#    this window, independent of the cursor, recovering only what is missing.
#    48 h covers a weekend outage.
INGEST_SWEEP_HOURS = int(os.environ.get("INGEST_SWEEP_HOURS", "48"))

# Sweep cadence. The cycle runs every 5 min; sweeping on every round would be
# waste, and an hour of latency on alerts already hours late changes nothing.
INGEST_SWEEP_INTERVAL_MINUTES = int(
    os.environ.get("INGEST_SWEEP_INTERVAL_MINUTES", "60"))

# --- Model: DeepSeek (cloud API, OpenAI-compatible) -------------------------
#
# The only inference path: this machine has neither a GPU nor the RAM for a
# continuously loaded model, and there is no local fallback. DeepSeek exposes an
# OpenAI-compatible API (/chat/completions, Bearer token). MAJOR security
# consequence: SOC data leaves the host. Pseudonymisation is IN PLACE and
# mandatory (`anonymize.py`): stable tokens per incident, `check_leak` refuses
# the call if a real value survived, rehydration on the answer so the analyst
# sees the real values in IRIS. Not to be confused with `sanitize.py`, which
# neutralises hostile text — another problem, another module.
#
# No grammar constraint is possible: DeepSeek guarantees valid JSON
# (response_format), not that the schema or the enum is respected. So the barrier
# is in the code: coercion/validation in triage.py, on top of the deterministic
# guardrails of actions.py.
DEEPSEEK_API_KEY = _required("DEEPSEEK_API_KEY")
# The v4 models reason: the reasoning tokens (reasoning_content) are charged
# against max_tokens BEFORE the content. Too small a budget (the old 400,
# calibrated on the non-reasoning chat model) is entirely eaten by the reasoning
# -> finish_reason=length and EMPTY content. Room is needed for the reasoning
# plus the verdict JSON.
TRIAGE_MAX_TOKENS = int(os.environ.get("TRIAGE_MAX_TOKENS", "6000"))
# Cap on the size of the triage PROMPT (input). Past it the incident used to be
# skipped — which silenced the biggest and most serious ones. Raised to 5000.
PROMPT_TOKENS_CAP = int(os.environ.get("TRIAGE_PROMPT_MAX_TOKENS", "5000"))
# The TP report is a multi-section markdown narrative, longer than the verdict;
# with the reasoning on top it needs even more room.
#
# 6000 was not enough. Measured during a purple-team exercise: two AD incident
# reports (several thousand alerts, 20 rules shown to the model) returned
# `finish_reason=length` with EMPTY content — the reasoning had eaten the whole
# budget. The fallback then wrote `triage.reason` BOTH into `summary` and into
# `analysis`, hence two identical sections in the report. The reports that did
# complete already consumed 4000-5700 tokens of content: 6000 left no room for
# the reasoning. 14000 gives the margin.
REPORT_MAX_TOKENS = int(os.environ.get("REPORT_MAX_TOKENS", "14000"))
# Case name: a tiny output (code name plus short title) but the model reasons
# anyway — it needs enough not to truncate before the JSON.
CASE_NAME_MAX_TOKENS = int(os.environ.get("CASE_NAME_MAX_TOKENS", "1500"))
# Answer to a WHITELIST task (decision or question): a short output, but the
# same reasoning margin as the case name.
WHITELIST_TASK_MAX_TOKENS = int(os.environ.get("WHITELIST_TASK_MAX_TOKENS", "1500"))
DEEPSEEK_URL = os.environ.get("DEEPSEEK_URL", "https://api.deepseek.com")
# deepseek-chat is deprecated (the API no longer accepts it, 400). Current
# tiers: deepseek-v4-flash (fast and cheap, the closest equivalent to the chat
# model the pipeline was calibrated on) and deepseek-v4-pro (a more robust
# verdict).
DEEPSEEK_MODEL = os.environ.get("DEEPSEEK_MODEL", "deepseek-v4-flash")

# LLM call timeouts, in seconds: (connect, read).
#
# The two count separately in `requests`, and the second is an INACTIVITY delay,
# not a total duration: a server sending one byte every 100 s never triggers a
# 120 s read timeout. That is why they are explicit here rather than hard-coded —
# a slow or partially broken provider must not tie up the cycle, which holds its
# advisory lock for its whole run.
#
# Short connect (10 s): if the TCP does not establish, retrying later is the
# right answer. Long read (120 s): a reasoning model takes time to produce the
# first byte, and cutting too early wastes tokens already paid for.
LLM_TIMEOUT_CONNECT_S = float(os.environ.get("LLM_TIMEOUT_CONNECT_S", "10"))
LLM_TIMEOUT_READ_S = float(os.environ.get("LLM_TIMEOUT_READ_S", "120"))


# --- DFIR-IRIS (case management) --------------------------------------------
#
# One case per triaged incident. The pipeline writes there through
# dfir-iris-client directly (deterministic); the IRIS MCP server serves the
# interactive investigation.
IRIS_URL = os.environ.get("IRIS_URL", "https://127.0.0.1:8443")
IRIS_API_KEY = os.environ.get("IRIS_API_KEY", "")
# Self-signed certificate on the loopback. Set to true if IRIS is exposed.
IRIS_VERIFY_TLS = os.environ.get("IRIS_VERIFY_TLS", "false").lower() == "true"
# IRIS client (the "customer" record) attached to the cases. 1 = default one.
IRIS_CUSTOMER = int(os.environ.get("IRIS_CUSTOMER", "1"))

# Maximum number of alerts LOADED to build a case. A flood incident lines up
# tens of thousands (on 2026-08-14: 126,508 on a single pfSense incident, 96,804
# on another): loading them all, `raw` included, blows up the cycle's memory and
# produces a case no analyst can read. We take the OLDEST and the most RECENT in
# equal shares — the start of the attack carries the seed, the end carries the
# current state; it is the middle of a repetitive burst that teaches nothing.
# `alert_count` remains the REAL count and is never truncated.
INCIDENT_MAX_ALERTS = int(os.environ.get("INCIDENT_MAX_ALERTS", "2000"))

# Maximum number of Evidence pieces set on a case. One piece per alert is the
# right granularity for a normal incident (a few dozen); past that, the Evidence
# tab becomes unusable and the IRIS database swells (on 2026-08-14: 8.3 GB for a
# single case). The cap covers the case TOTAL, accumulated across passes, not the
# burst.
EVIDENCE_MAX_PER_CASE = int(os.environ.get("EVIDENCE_MAX_PER_CASE", "500"))

# --- Pivot link to the Wazuh dashboard --------------------------------------
#
# Every IRIS timeline event carries a Discover link filtered on its rule
# and its agent: the analyst goes from the case to the raw Wazuh log in one
# click. The URL is seen from the analyst's BROWSER (not from this host) — hence
# a default on the public host name rather than the loopback; to be adjusted.
# The Discover path depends on the dashboard version (OpenSearch Dashboards 2.x
# on Wazuh 4.9 = /app/data-explorer/discover): overridable if needed.
# No usable default: "localhost" would point at the analyst's own machine (the
# link is opened from THEIR browser, not from this host) and would break the
# link. To be set in .env with the URL of the dashboard that is actually
# reachable (e.g. https://soc.example.local).
WAZUH_DASHBOARD_URL = os.environ.get("WAZUH_DASHBOARD_URL", "")
WAZUH_DASHBOARD_DISCOVER_PATH = os.environ.get(
    "WAZUH_DASHBOARD_DISCOVER_PATH", "/app/data-explorer/discover")
# Index pattern covering the indices actually fed (see the wazuh-linux/web
# routing). "soc-ai-all-alerts" already exists on the dashboard side.
WAZUH_DASHBOARD_INDEX_PATTERN = os.environ.get(
    "WAZUH_DASHBOARD_INDEX_PATTERN", "soc-ai-all-alerts")

# --- Internal subnets of the estate -----------------------------------------
#
# Used to qualify IP IOCs: a /dev/tcp target or a source IP INSIDE these ranges
# is internal lateral movement, NOT a C2. Do NOT equate "RFC1918 private" with
# "internal": a C2 can itself be in RFC1918 (VPN, private cloud...) — classifying
# it as internal would whitewash it. List the subnets of the monitored estate
# explicitly; everything else (including an RFC1918 C2) is external.
NETWORKS_INTERNAL = [
    r.strip() for r in os.environ.get("NETWORKS_INTERNAL", "").split(",")
    if r.strip()]

# --- Remediation (executing the actions) ------------------------------------
#
# The move from "propose" to "execute". Two write channels:
#  - Shuffle SOAR (webhooks) for host isolation and process kill: existing
#    workflows, reversible, Shuffle carries the Wazuh auth.
#  - the Wazuh API directly for IP blocking and account disabling (no dedicated
#    Shuffle workflow). Active response pushed over 1514.
#
# MITIGATE_EXECUTE=false by default: DRY-RUN. Nothing actually fires, the module
# shows the payload and writes IRIS notes marked [SIMULATION]. A high-impact
# action on production must not arm itself by accident.
MITIGATE_EXECUTE = os.environ.get("MITIGATE_EXECUTE", "false").lower() == "true"

# Maximum number of emissions of the same remediation left at 'sent' (it went
# out but was never confirmed by an `ar-result`). Past it we stop re-emitting: a
# fire-and-forget channel that never confirms must not be hit on every cycle
# forever. 3: two retries after the first attempt.
MITIGATE_MAX_ATTEMPTS = int(os.environ.get("MITIGATE_MAX_ATTEMPTS", "3"))

# Minimum interval (s) between two Wazuh active responses emitted. A burst of
# ARs of the same command towards the same agent saturates `wazuh-execd`, which
# silently drops part of them BEFORE the script (purple-team #3: 2 quarantines
# per agent lost, no log and no `ar-result`). We serialise the sends on the
# emitter side.
MITIGATE_AR_GAP_SECONDS = float(os.environ.get("MITIGATE_AR_GAP_SECONDS", "1.5"))

SHUFFLE_URL = os.environ.get("SHUFFLE_URL", "http://localhost:5001")
SHUFFLE_WEBHOOK_ISOLATE = os.environ.get(
    "SHUFFLE_WEBHOOK_ISOLATE", "webhook_00000000-0000-0000-0000-00000000a001")
SHUFFLE_WEBHOOK_KILL = os.environ.get(
    "SHUFFLE_WEBHOOK_KILL", "webhook_00000000-0000-0000-0000-00000000a002")

# Wazuh API (wazuh-wui user). Same password as API_PASSWORD in wazuh/.env.
WAZUH_API_URL = os.environ.get("WAZUH_API_URL", "https://127.0.0.1:55000")
WAZUH_API_USER = os.environ.get("WAZUH_API_USER", "wazuh-wui")
WAZUH_API_PASSWORD = os.environ.get("WAZUH_API_PASSWORD", "")

# SSH to the agents, to read the isolation marker (/var/ossec/isolated).
# Reserved for READING state: never a shell driven by the LLM (see CLAUDE.md).
# The isolation rule only allows SSH from the manager — so this reader must run
# on the manager host to stay reliable even on an isolated agent.
SSH_KEY = os.path.expanduser(
    os.environ.get("SSH_KEY", "~/.ssh/wazuh_ops_ed25519"))
SSH_USER = os.environ.get("SSH_USER", "wazuh-admin")
ISOLATION_MARKER = os.environ.get("ISOLATION_MARKER", "/var/ossec/isolated")

# Agents no remediation may ever target, whatever the verdict. 000 is the
# manager: isolating it cuts the collection of the WHOLE estate, the console, the
# API — hence the only channel through which it could be un-isolated. That is a
# SOC suicide, and it is not hypothetical: on 2026-07-29 a YARA incident carried
# by the `wazuh.manager` agent (YARITRUST alerts are emitted by the manager,
# while the suspicious file is on ANOTHER machine) produced
# `propose_isolate_host` on 000. The action went out; only the absence of `nft`
# in the container made it harmless.
#
# To be kept at the front of the deterministic guardrails: the model only sees an
# `agent_id` in its context and has no way of knowing which one carries the
# SOC.
AGENTS_PROTECTED = {
    a.strip() for a in os.environ.get("AGENTS_PROTECTED", "000").split(",")
    if a.strip()}

# "Host sensor" agents: their telemetry describes the activity of OTHER machines
# (e.g. the auditd of the Proxmox host sees the execve of its LXC containers and
# attributes them to itself). A remediation must NEVER target such an agent: the
# real theatre is elsewhere (the container), and acting on the sensor is either
# useless (disabling an account that does not live there — the bug observed) or
# too broad (isolating the whole host for a single container). When in doubt
# about the real machine, we do not act.
#
# Two forms, the second often forgotten:
#
#  - HOST sensor: the Proxmox host of a fleet of LXCs, whose auditd sees the
#    execve of every container and attributes them to itself. Isolating the host
#    for a single container cuts everything it hosts.
#  - NETWORK sensor: the gateway carrying the IDS and the firewall. Suricata and
#    filterlog describe the traffic of OTHER machines, but the alerts carry the
#    gateway's agent. A C2 beacon emitted by a LAN workstation therefore opens an
#    incident on the firewall's agent — and a remediation computed on that would
#    target the equipment routing the whole network, SOC included. Observed on
#    2026-08-11: incident #2697 (926 C2 alerts) attributed to home-r-pf01 while
#    the guilty machine was 192.168.5.15.
#
# No default: to be listed explicitly per deployment (Wazuh agent id) through
# AGENTS_SENSORS.
AGENTS_SENSORS = {
    a.strip() for a in os.environ.get("AGENTS_SENSORS", "").split(",")
    if a.strip()}

# Agents running Windows: the same logical action (isolate, block, kill, disable
# an account) goes out on a different active response depending on the OS — the
# Windows/AD scripts (wazuh/active-response/windows/) instead of the Linux .sh.
# No default: to be listed explicitly per deployment (Wazuh agent id).
AGENTS_WINDOWS = {
    a.strip() for a in os.environ.get("AGENTS_WINDOWS", "").split(",")
    if a.strip()}

# Domain controllers: EXECUTORS of the domain actions (disabling an AD account,
# removing from a privileged group). A domain action does NOT go out on the
# compromised member host — the account is not local there — but on a DC,
# whatever host the evidence appeared on (the inverse analogue of
# AGENTS_SENSORS). No default: to be listed explicitly per deployment (Wazuh
# agent id).
AGENTS_DC = {
    a.strip() for a in os.environ.get("AGENTS_DC", "").split(",")
    if a.strip()}

# IP(s) that the isolation of a Windows host leaves reachable (the Wazuh
# manager, so the agent keeps reporting and the SOC can investigate over WinRM).
# Passed as extra_args to win-host-isolate.exe. No default: to be set per
# deployment (the manager IP as the agent reaches it).
MITIGATE_ISOLATE_ALLOW = [
    ip.strip() for ip in os.environ.get("MITIGATE_ISOLATE_ALLOW", "").split(",")
    if ip.strip()]

# Wazuh rules that signal an ACTIVE COMPROMISE of the host itself: confirmed
# post-exploitation (the attacker already runs code on the machine), not a mere
# inbound attempt. Used by the isolation guardrail: on these rules, isolation is
# NO LONGER downgraded to a less invasive containment (blocking an IP will not
# dislodge an attacker already in — reverse shell, rootkit, root persistence, a
# webshell that executes). Measured at the purple-team of 2026-07-31: the web
# host .15, with RCE + webshell + root persistence + rootkit under way, only
# received a block_ip (isolation dropped) and stayed reachable.
#
# We list IDENTIFIERS (stable), not description text (see the rule_desc trap of
# correlate.py). Categories: webshell that executes (100701/710/750), reverse
# shell / C2 / tunnel (100650/651/652/764), rootkit / kernel implant /
# ld.so.preload (100748/760/763/772, 521), root persistence
# (100740/741/742/749/770), credential access (100643/653). NOT the inbound web
# probes alone (100700 RCE-attempt, 100702 LFI/SQLi): a scanner hitting a URL is
# not a compromise — that is exactly the case the isolation guardrail protects
# (block_ip is enough). The set is overridable from the environment.
RULES_COMPROMISE_HOST = {
    r.strip() for r in os.environ.get(
        "RULES_COMPROMISE_HOST",
        "100701,100710,100750,"          # webshell: command executed
        "100650,100651,100652,100764,"   # reverse shell / C2 / outbound tunnel
        "100748,100760,100763,100772,521,"  # rootkit / kernel / ld.so.preload
        "100740,100741,100742,100749,100770,"  # root persistence
        "100643,100653").split(",")      # /etc/shadow access
    if r.strip()}

# Wazuh groups whose agents are NEVER isolated from the network.
#
# Isolation must only concern ENDPOINTS — machines whose network can be cut
# without cutting everyone else's. A firewall, a reverse proxy, a DNS resolver or
# a VPN gateway route OTHER people's traffic: isolating them does not contain the
# incident, it causes a general outage, and on a firewall it also cuts the link
# through which the situation would be restored.
#
# The role is carried by the Wazuh groups rather than by a hard-coded list of
# ids: it is the native inventory mechanism, it survives adding an agent, and the
# operator enrolling a machine declares its role in the same place as the rest of
# its configuration. See wazuh/README.md for creating the group.
ISOLATION_FORBIDDEN_GROUPS = {
    g.strip().lower()
    for g in os.environ.get("ISOLATION_FORBIDDEN_GROUPS", "infrastructure").split(",")
    if g.strip()}

# What to do when the groups of an agent CANNOT be known (API unreachable, agent
# deleted): by default we refuse isolation.
#
# It is a choice, and it is the guardrail's plain sense: isolation is the most
# destructive action of the catalogue, and being unable to check that a machine
# is an endpoint is a reason to abstain, not to try. The worst case of a refusal
# is an uncontained incident the analyst sees in the case (the action switches to
# escalate_human); the worst case of an authorisation by default is the site
# firewall cut over an API outage.
ISOLATION_REFUSE_IF_ROLE_UNKNOWN = os.environ.get(
    "ISOLATION_REFUSE_IF_ROLE_UNKNOWN", "true").lower() == "true"


# --- CMDB: asset role and priority (assets.py) ------------------------------
#
# Not all machines are equal. The same behaviour — an unseen binary executing, an
# account created — does not have the same reach on a domain controller and on a
# test box. Until now the pipeline only knew `rule_level`, which describes the
# RULE and not the MACHINE: a level 12 on the DC and a level 12 on a disposable
# workstation landed in the same queue, in the same order, with the same
# guardrails.
#
# The role is carried by the Wazuh groups (the native inventory mechanism,
# already used by ISOLATION_FORBIDDEN_GROUPS), prefixed so they do not collide
# with the configuration groups: `role-dc`, `role-firewall`...
CMDB_GROUP_PREFIX = os.environ.get("CMDB_GROUP_PREFIX", "role-")

# Role -> priority (1 = the most critical). The ranking follows what is lost if
# the machine falls:
#
#  P1 — the compromise loses the domain (dc), the network (firewall), the
#       detection capability (soc), everything hosted (hypervisor), trust (pki)
#       or the ability to restore (backup).
#  P2 — exposed service or data carrier: the classic pivot of an intrusion.
#  P3 — internal server with no exposure and no sensitive data.
#  P4 — client workstation, lab, ephemeral machine, and any undeclared role.
PRIORITY_ROLES: dict[str, int] = {
    "dc": 1, "firewall": 1, "soc": 1, "hypervisor": 1, "pki": 1, "backup": 1,
    "web": 2, "db": 2, "mail": 2, "proxy": 2, "dns": 2, "vpn": 2,
    "fileserver": 2,
    "serveur": 3, "admin": 3,
    "endpoint": 4, "lab": 4,
}
# Override/addition per deployment: PRIORITY_ROLES="nas=1,jellyfin=3".
for _pair in os.environ.get("PRIORITY_ROLES", "").split(","):
    if "=" in _pair:
        _role, _p = _pair.split("=", 1)
        try:
            PRIORITY_ROLES[_role.strip().lower()] = int(_p)
        except ValueError:
            sys.exit(f"PRIORITY_ROLES: invalid priority in \"{_pair}\"")

# Priority of a machine whose role is NOT declared (no `role-` group, agent
# absent from the CMDB, API unreachable). P4: an operator decision — an
# undeclared asset does not take the place of a critical one in the queue.
#
# The downside is real: an important machine never declared is treated as a
# disposable workstation. That is why the source of the priority is RECORDED
# (`assets.priority_source = 'default'`) and reported by the coverage report —
# the inventory debt must be visible, not guessed.
DEFAULT_PRIORITY = int(os.environ.get("DEFAULT_PRIORITY", "4"))

# Offset applied to the Wazuh level to obtain the EFFECTIVE severity of the
# incident, per priority (P1..P4). `max_level` is never modified: it describes
# what the rule saw, and all the rest of the pipeline (correlation, UEBA,
# RULES_COMPROMISE_HOST) relies on it. The severity is a second quantity, which
# adds "on what".
SEVERITY_BONUS_PRIORITY = {
    p + 1: int(v) for p, v in enumerate(
        os.environ.get("SEVERITY_BONUS_PRIORITY", "2,1,0,-1").split(","))}

# Level from which an automatic false-positive closure is forbidden, PER
# PRIORITY (see actions.apply_guardrails). On a P1 asset we do not let the model
# close a level-12 incident: the cost of a false negative there is nothing like
# the cost of one more case to read.
CLOSURE_FORBIDDEN_BY_PRIORITY = {
    p + 1: int(v) for p, v in enumerate(
        os.environ.get("CLOSURE_FORBIDDEN_BY_PRIORITY", "12,13,14,14").split(","))}

# Priority forced for a SENSOR agent (AGENTS_SENSORS). Its telemetry describes
# the activity of OTHER machines: the firewall carrying Suricata is indeed a P1
# asset, but the alerts it REPORTS are about LAN workstations. Without this
# fallback, every scan seen by the IDS would become a P1 incident and drown the
# queue — prioritisation would degrade the ordering instead of improving it.
PRIORITY_SENSOR = int(os.environ.get("PRIORITY_SENSOR", "3"))


# --- Correlation ------------------------------------------------------------
#
# Two alerts of the same agent less than CORRELATION_GAP_MINUTES apart and
# sharing common ground (MITRE tactic, rule group or entity) are attached to the
# same incident. Proximity chaining: A-B and B-C also attach A-C, even when A and
# C are far apart.
CORRELATION_GAP_MINUTES = int(os.environ.get("CORRELATION_GAP_MINUTES", "30"))

# Widened window for STRONG links — same source IP, same file, same account. A
# hostile IP coming back three times in a day is one campaign; with the 30-minute
# window alone it produced three distinct incidents, hence three LLM triages for
# the same subject.
ENTITY_GAP_MINUTES = int(os.environ.get("ENTITY_GAP_MINUTES", "360"))

# Guardrail against endless chaining: on a noisy host, one alert every 25
# minutes would merge a whole week into a single unreadable incident.
MAX_INCIDENT_HOURS = int(os.environ.get("MAX_INCIDENT_HOURS", "6"))

# CAMPAIGN merge window: incidents from several hosts gathered into a single
# case when they share a STRONG marker belonging to the attacker (created
# account, external C2 IP, malicious file). Wider than MAX_INCIDENT_HOURS because
# a campaign spreads over days; the risk of over-merging is bounded by the
# requirement of a shared attacker marker (never an internal IP nor a generic
# entity). 0 disables the campaign merge.
CAMPAIGN_GAP_HOURS = int(os.environ.get("CAMPAIGN_GAP_HOURS", "48"))

# Lifetime of the automatic RE-TRIAGE of an incident (fix #4, the token
# explosion of 2026-07-30). Past this delay from `first_seen`, an
# already-triaged incident is no longer re-triaged even when it gains alerts
# (`needs_refresh`): otherwise an incident from the noisy estate gets
# re-analysed by the LLM every 5 min for life (observed: incidents several days
# old still burning 18-25 LLM calls a day). A new intrusion reopens a fresh
# incident through the correlation windows anyway. 0 disables the cap (re-triage
# with no age limit). Does NOT affect creation (an incident never triaged is
# always triaged, whatever its age).
INCIDENT_REFRESH_TTL_HOURS = int(
    os.environ.get("INCIDENT_REFRESH_TTL_HOURS", "48"))

# --- "Silent sensor" watchdog (watchdog.py) ---------------------------------
# A sensor that was talking and goes quiet is a blind spot no rule sees. The rule
# groups watched: their silence makes whole swathes of the ruleset inert (audit
# -> 1006xx/1007xx; suricata -> network detection; sshd/pam -> brute-force).
# Adding an application group is easy if needed.
WATCHDOG_SENSORS = tuple(os.environ.get(
    "WATCHDOG_SENSORS", "audit,suricata,sshd,syscheck").split(","))
# Reference window: over how many hours a sensor is judged "established".
WATCHDOG_REF_HOURS = int(os.environ.get("WATCHDOG_REF_HOURS", "168"))  # 7 j
# Minimum volume over the reference window so as not to alert on an anecdotal
# sensor (a single isolated event is not a baseline).
WATCHDOG_BASELINE_MIN = int(os.environ.get("WATCHDOG_BASELINE_MIN", "20"))
# Silence tolerated before declaring the OUTAGE. 10 min, an operator setting of
# 2026-08-11, consistent with the real cadence of the continuous sensors measured
# over 7 days of data: gap between two events, p95 / max
#
#     audit      5.4 min / 8.3 min
#     suricata   0.0 min / 3.7 min
#
# A 10-minute silence on those two is therefore no longer explained by a lull in
# traffic. The EVENT-DRIVEN sensors (sshd, syscheck) have their own threshold
# below: for them silence is the normal state.
WATCHDOG_SILENCE_MINUTES = int(os.environ.get("WATCHDOG_SILENCE_MINUTES", "10"))

# PER-SENSOR threshold, for those that do not emit continuously.
#
# syscheck is not a stream: FIM only alerts on a CHANGE (rules
# 550/553/554/594/750 — there is no end-of-scan event to hook onto), and the
# scheduled scan runs every 12 h (Wazuh default, no <frequency> in the shared
# agent.conf). A quiet estate therefore produces nothing for hours, which is the
# intended behaviour. With the 90-minute default, the watchdog cried "silent
# sensor" on every agent every day between noon and 11 p.m.: a permanent alarm
# that teaches people to ignore the watchdog, which costs more than the gap it
# claims to cover.
#
# 840 min (a 12 h cycle plus 2 h) was still too short, and 2026-08-12 showed it:
# case #212 opened on `admin` for a perfectly healthy sensor. The scan ran on
# schedule (last on 2026-08-11 23:12, 2004 files tracked), and the last CHANGE
# dated from 2026-08-10 — an `update-ca-certificates`. Nothing had simply
# happened on that machine since.
#
# Maximum gap actually observed between two syscheck events, over 30 days:
#
#     wazuh.manager  52 h        debian2  19 h
#     admin          29 h        debian3  17 h
#
# 4320 min (3 d) sits above the measured maximum with margin. It is an
# acknowledged patch: the right signal for this sensor is not the alert (which
# depends on a change) but the SCAN itself, which the Wazuh API exposes
# (`/syscheck/<agent>/last_scan`). Until we read it, a genuinely stuck syscheckd
# stays invisible for up to three days.
#
# sshd follows the same reasoning, measured on 2026-08-11 over 7 days: median gap
# between two events 0.2 min, but p95 at 254 min and maximum at 63 h. A host
# nobody logs into emits NOTHING, and that is normal — at a 10-minute threshold,
# every idle machine would be declared down. Worse, a host isolated by
# remediation only accepts SSH from the manager: its sshd sensor goes quiet by
# construction (observed on debian2/3/4, silent since 2026-08-09 because
# isolated, not because broken).
#
# 1440 min (24 h): beyond that, even a forgotten machine should have seen a
# session or a scan. A genuinely stuck journald reader therefore does come out
# eventually, without drowning the analyst in the meantime.
WATCHDOG_SILENCE_PER_SENSOR = {
    "syscheck": int(os.environ.get("WATCHDOG_SILENCE_SYSCHECK", "4320")),
    "sshd": int(os.environ.get("WATCHDOG_SILENCE_SSHD", "1440")),
}

# Where an outage lands in IRIS: `alert` | `case` | `off`.
#
# A silent sensor is a blind spot of the SOC itself: it deserves a record someone
# must acknowledge, not only a log line nobody reads. The question is WHERE.
#
# `case` was the first choice, and it was the wrong one: a case is an
# investigation file, with its notes, its timeline, its IOCs. A sensor outage has
# nothing to investigate — it has a state (silent / recovered) and a gesture
# (acknowledge, or go and repair). The outage cases mixed with the incident cases
# in the same queue, where they diluted what matters.
#
# `alert` (the default since 2026-08-13) files them in the Alerts tab, which
# carries exactly that life cycle (New / Assigned / Closed) and leaves the
# "Escalate to case" button to the analyst: THEY decide an outage deserves a
# file, which the `case` channel decided in their place.
#
# `case` stays available, and outages opened BEFORE a switch are closed in their
# original channel (see watchdog.monitor).
WATCHDOG_IRIS_CHANNEL = os.environ.get("WATCHDOG_IRIS_CHANNEL", "alert").lower()
# Backwards compatibility: `WATCHDOG_CASE_IRIS=false` used to cut every IRIS record.
if os.environ.get("WATCHDOG_CASE_IRIS", "true").lower() != "true":
    WATCHDOG_IRIS_CHANNEL = "off"
if WATCHDOG_IRIS_CHANNEL not in ("alert", "case", "off"):
    WATCHDOG_IRIS_CHANNEL = "alert"

# Ingestion lag beyond which the watchdog goes quiet rather than shouting.
#
# It measures sensor silence against the ingestion horizon, not against the
# clock. If ingestion itself stalls, that horizon freezes: no sensor looks silent
# any more and the watch becomes a quiet lie. So we detect that case separately,
# against the clock this time, and suspend the rest — a stopped pipeline is ONE
# outage, not one per sensor.
#
# 30 min = six ingestion cycles (300 s): beyond that, it is no longer a cycle
# running late.
WATCHDOG_INGEST_LAG_MAX = int(
    os.environ.get("WATCHDOG_INGEST_LAG_MAX", "30"))

# --- Log source routing (routing.py) ----------------------------------------
#
# The watchdog checks that every log source falls into ITS index, and creates the
# missing index set when a new source appears. It is the active counterpart of
# the INDEXER_ALERT_INDICES list above: maintaining that list by hand has already
# blinded the AI twice (wazuh-linux/web, then yara and firewall). What is checked
# on every pass can no longer be forgotten.
ROUTING_ACTIVE = os.environ.get("ROUTING_ACTIVE", "true").lower() == "true"

# Auto-application of the index sets. `false` = sources are detected, named and
# proposed (IRIS alert), but nothing is written on the indexer side: that is the
# observation mode to keep for a few days after a deployment.
ROUTING_APPLY = os.environ.get("ROUTING_APPLY", "true").lower() == "true"

# The target ingest pipeline. The name is imposed by filebeat (wazuh module),
# not by us: it is the one the manager pushes back on every start.
ROUTING_PIPELINE = os.environ.get(
    "ROUTING_PIPELINE", "filebeat-7.10.2-wazuh-alerts-pipeline")

# Observation window for the sources. 24 h: wide enough for a daily source
# (nightly backup, daily report) to be seen, short enough for the aggregation to
# stay free.
ROUTING_WINDOW_HOURS = int(os.environ.get("ROUTING_WINDOW_HOURS", "24"))

# Minimum volume to CREATE an index set. A source that produced three lines
# yesterday is not a source, it is an accident — and an index set created for
# nothing then stays in the template, in the ISM and in the dashboard's combined
# pattern, where an empty pattern breaks Global (see create_index_patterns.py).
ROUTING_BASELINE_MIN = int(os.environ.get("ROUTING_BASELINE_MIN", "20"))

# Minimum volume to report a DRIFT (a known source no longer landing where it
# should). Lower than for creation: noticing that an existing route no longer
# works commits no write, and it is the symptom of an overwritten pipeline — we
# want to see it early.
ROUTING_DRIFT_MIN = int(os.environ.get("ROUTING_DRIFT_MIN", "5"))

# Silence beyond which an ESTABLISHED source is declared silent. Measured on the
# indexer, hence against the clock (unlike the watchdog sensors, measured against
# the ingestion horizon).
#
# 48 h and not 10 minutes: a log source is not a continuous sensor. A proxy can
# log nothing alertable for a whole night. This threshold is what would have
# flagged wazuh-proxy, wazuh-jellyfin and wazuh-dns, dead since 2026-07-30
# without anything saying so.
ROUTING_SILENCE_HOURS = int(os.environ.get("ROUTING_SILENCE_HOURS", "48"))

# Cap on automatic creations per 24 h. A low cap is deliberate: creating an
# index set touches the ingest pipeline of the WHOLE SOC. If ten new sources
# appear on the same day, what is needed is not ten index sets, it is a human
# looking at what just changed in the estate.
ROUTING_MAX_NEW_PER_DAY = int(
    os.environ.get("ROUTING_MAX_NEW_PER_DAY", "2"))

# Wazuh's default index: a source landing there is routed by nothing.
ROUTING_DEFAULT_INDEX = os.environ.get("ROUTING_DEFAULT_INDEX", "wazuh-alerts-4.x")

# OpenSearch Dashboards, to create the index pattern of a new index set. Without
# it the index exists and fills up, but stays invisible in Discover — the kind of
# half-creation discovered three weeks later.
DASHBOARD_URL = os.environ.get("DASHBOARD_URL", "https://localhost")

# Command reconstruction (IRIS report): the compromised account is often also a
# legitimate session (the same uid generates login noise — gpg-agent, systemd
# generators). We only show the commands ATTACHED to the attack: those forming a
# temporal cluster (max gap below) touching a malicious alert. Session noise,
# separated by a longer silence, is dropped. Wide enough to keep a
# recon -> exploit -> persistence chain contiguous, short enough to cut the
# session-init burst.
COMMAND_CLUSTER_GAP_S = int(os.environ.get("COMMAND_CLUSTER_GAP_S", "60"))

# --- Automatic whitelist ----------------------------------------------------
#
# Number of distinct incidents judged false_positive, on the same signature,
# before an exception is created automatically. A single FP can be an accident;
# recurrence is the signal.
WHITELIST_MIN_FP = int(os.environ.get("WHITELIST_MIN_FP", "3"))

# --- AI metrics exported to the indexer (metrics.py) ------------------------
#
# A dedicated index rather than a field in the alerts: these documents are not
# alerts, they have neither agent nor rule, and mixing them would skew every
# existing alert counter.
METRICS_INDEX_PREFIX = os.environ.get("METRICS_INDEX_PREFIX", "wazuh-ai")

# Window re-exported on every pass. Far larger than the job cadence (5 min): the
# export being idempotent (deterministic _id), a wide overlap catches up a few
# hours of indexer outage for free.
METRICS_WINDOW = os.environ.get("METRICS_WINDOW", "6h")

# Model pricing, in USD per million tokens. Published values for
# deepseek-v4-flash (as of 2026-07-29):
#     input cache miss 0.14 - input cache hit 0.0028 - output 0.28
#
# APPROXIMATE, and it must be said: these rates are read from the public grid,
# not from an invoice. Cross-checked against the account's real consumption —
# 671,593 tokens billed 0.09 USD, that is 0.134 USD/M across all tokens,
# consistent with 0.14 on input for overwhelmingly inbound traffic. The order of
# magnitude is right; do not use it for rebilling.
#
# A cache hit is 50x cheaper than a cache miss: on this pipeline the system
# prompt is constant from one incident to the next, so a growing share of the
# input is cached. We read the split returned by the API when it is available;
# otherwise we count EVERYTHING as cache miss, which overstates the cost (an
# overestimate beats an underestimate).
LLM_COST_USD_PER_MTOKEN_IN = float(
    os.environ.get("LLM_COST_USD_PER_MTOKEN_IN", "0.14"))
LLM_COST_USD_PER_MTOKEN_IN_CACHE = float(
    os.environ.get("LLM_COST_USD_PER_MTOKEN_IN_CACHE", "0.0028"))
LLM_COST_USD_PER_MTOKEN_OUT = float(
    os.environ.get("LLM_COST_USD_PER_MTOKEN_OUT", "0.28"))

# --- VOC: vulnerability management (vulns.py) -------------------------------
#
# Wazuh's Vulnerability Detection module writes into a STATE index
# (`wazuh-states-vulnerabilities-*`): the document of a fixed vulnerability is
# DELETED, not archived. So it always shows "where we stand", never "are we
# making progress". A VOC needs the second question — burn-down, remediation
# MTTR, SLA compliance — and it can only be answered with a history one has to
# build oneself. That is the whole point of vulns.py.
VULN_INDICES = os.environ.get("VULN_INDICES", "wazuh-states-vulnerabilities-*")

# VOC export index, distinct from `wazuh-ai-*`: these are neither alerts nor AI
# metrics, and mixing them would skew the counters of both.
VOC_INDEX_PREFIX = os.environ.get("VOC_INDEX_PREFIX", "wazuh-voc")

# Weight of a vulnerability by severity, for the risk aggregate. A deliberately
# VERY non-linear scale: it takes ten Medium, or fifty Low, to weigh a single
# Critical. A score adding them at equal weight would be dominated by the
# background noise of the distributions (2,500 open CVEs on an up-to-date Debian,
# overwhelmingly Low/Medium with no known exploit) and would rank machines by
# number of installed packages.
VULN_SEVERITY_WEIGHT = {
    "critical": 10.0, "high": 4.0, "medium": 1.0, "low": 0.2,
    # Severity missing from the feed (334 per Debian host measured on
    # 2026-08-12): neither ignored — it is a real CVE — nor treated as serious.
    "": 0.5, "untriaged": 0.5, "unknown": 0.5,
}

# Risk multiplier by CMDB priority (P1..P4). Same logic as
# `SEVERITY_BONUS_PRIORITY` on incidents: a critical CVE on the domain controller
# and the same one on a lab box are not the same problem, and a VOC counting them
# alike makes patching happen in the wrong order.
VOC_PRIORITY_FACTOR = {
    p + 1: float(v) for p, v in enumerate(
        os.environ.get("VOC_PRIORITY_FACTOR", "4,2,1,0.5").split(","))}

# Expected fix delay, IN DAYS, by severity then by priority (P1..P4). These are
# service objectives, not a standard: they come from plain sense ("a critical on
# the DC is handled within the week") and are tuned per deployment. Their only
# function is to make lateness MEASURABLE — without a deadline, "vulnerability
# open for 210 days" is just a number.
VOC_SLA_DAYS = {
    "critical": [7, 14, 30, 60],
    "high": [15, 30, 60, 90],
    "medium": [30, 60, 90, 180],
    "low": [90, 180, 365, 365],
}
for _line in os.environ.get("VOC_SLA_DAYS", "").split(";"):
    if ":" in _line:
        _sev, _days = _line.split(":", 1)
        try:
            _v = [int(j) for j in _days.split(",")]
        except ValueError:
            sys.exit(f"VOC_SLA_DAYS: non-integer value in \"{_line}\"")
        if len(_v) != 4:
            sys.exit(f"VOC_SLA_DAYS: 4 values (P1..P4) expected in \"{_line}\"")
        VOC_SLA_DAYS[_sev.strip().lower()] = _v

# Weighted load that is worth 100/100 in the exposure score. The score is
# log-compressed: the load ranges from a few units (a server kept up to date) to
# several tens of thousands (a Debian whose kernel meta-package drags 2,500
# CVEs), and a linear scale would crush the whole estate at the bottom. To be
# raised if most machines saturate at 100 — in which case the score sorts nothing
# any more and the raw counters, exported alongside, must be read.
VOC_MAX_LOAD = float(os.environ.get("VOC_MAX_LOAD", "20000"))

# Minimum severity from which an out-of-SLA vulnerability is exported document
# by document into the VOC index. Open Low/Medium ones count in the thousands and
# have no individual action value: they stay in the aggregates, not in the "to
# handle" table.
VOC_SEVERITIES_DETAIL = {
    s.strip().lower() for s in
    os.environ.get("VOC_SEVERITIES_DETAIL", "critical,high").split(",")
    if s.strip()}

# Number of CVEs listed by name in the "Exposition aux vulnerabilites" section
# of an IRIS case. Past that, the note becomes a catalogue nobody reads and the
# generated report overflows.
VOC_MAX_CVE_REPORT = int(os.environ.get("VOC_MAX_CVE_REPORT", "10"))

# --- Automatic tuning of the Wazuh rules (rule_tuning.py) -------------------
#
# The whitelist's second stage: instead of dropping the alert AFTERWARDS in the
# soc-agent, we generate a Wazuh child rule that neutralises it in the engine
# itself. The noise then costs neither indexing nor correlation.

# The manager's rule directory, mounted into the container. The same directory
# as the hand-written rules: one file per rule, alphabetical order.
RULE_TUNING_DIR = os.environ.get(
    "RULE_TUNING_DIR", "/wazuh-rules")

# Identifier range reserved for the generated rules. Separated from
# 1006xx-1009xx (hand-written rules) so a glance at the number tells the
# origin.
RULE_TUNING_ID_MIN = int(os.environ.get("RULE_TUNING_ID_MIN", "101000"))
RULE_TUNING_ID_MAX = int(os.environ.get("RULE_TUNING_ID_MAX", "101999"))

# Level applied by the exception. By DEFAULT we lower (5) instead of suppressing
# (0): the alert stays readable and auditable, it merely drops below MIN_LEVEL,
# hence no longer opens an incident. That is what distinguishes "calming a rule"
# from "invalidating it".
RULE_TUNING_LEVEL = int(os.environ.get("RULE_TUNING_LEVEL", "5"))

# Full suppression (level 0) makes the event disappear from the alerts: nothing
# left to read back the day the exonerated signature turns out to be a real
# attack. Locked behind an explicit flag.
RULE_TUNING_ALLOW_LEVEL_0 = os.environ.get(
    "RULE_TUNING_ALLOW_LEVEL_0", "false").lower() == "true"

# Cap on generated rules. Beyond it, this is no longer fine tuning: it is a
# ruleset that does not match the environment, and that is handled by hand.
RULE_TUNING_MAX_RULES = int(os.environ.get("RULE_TUNING_MAX_RULES", "50"))

# Alerts examined to find a counter-example (an event of the same parent rule
# NOT covered by the exception). Without a counter-example the rule is not
# deployed: we cannot prove it does not invalidate the parent.
RULE_TUNING_COUNTER_EXAMPLE_CANDIDATES = int(
    os.environ.get("RULE_TUNING_COUNTER_EXAMPLE_CANDIDATES", "200"))

# Manager restart (the only way to load a rule change): number of 5 s polls
# before concluding it failed and removing everything.
RULE_TUNING_WAIT_ATTEMPTS = int(os.environ.get("RULE_TUNING_WAIT_ATTEMPTS", "24"))

# Wazuh level from which we NEVER whitelist automatically, even on repeated FPs.
# Same logic as the closure guardrail: a rule firing at 14+ deserves a human
# before being neutralised. An attacker causing repeated FPs to get whitelisted
# stops at this wall.
WHITELIST_MAX_LEVEL = int(os.environ.get("WHITELIST_MAX_LEVEL", "14"))

# --- Training mode (learning the ambient noise, see training.py) ------------
#
# Commissioning window: the SOC plugged into an estate already in production
# first learns its noise, analysis pipeline suspended, before judging or
# remediating anything. Driven from the root .env by the administrator (read
# directly by docker compose up -d).
#
# TRAINING_ENABLED only opens a window on the VERY FIRST launch (no window in
# database): training is a commissioning phase, not a recurring mode. Reopening
# one later is an explicit decision (`python -m soc_agent.training --start`).
TRAINING_ENABLED = os.environ.get("TRAINING_ENABLED", "false").lower() == "true"
TRAINING_DAYS = int(os.environ.get("TRAINING_DAYS", "7"))

# Level from which an alert observed during the window is learned as noise.
# Aligned on MIN_LEVEL (12 = HIGH): below it, the alert does not open an incident
# anyway, so whitelisting it would bring nothing.
TRAINING_MIN_LEVEL = int(os.environ.get("TRAINING_MIN_LEVEL", "12"))

# A cap SPECIFIC to training, distinct from WHITELIST_MAX_LEVEL (14) which
# bounds the automatic whitelist in operation. Default 15: training must be able
# to learn CRITICAL noise, otherwise it does not calm what does the most damage
# (autonomous remediation on business traffic). That is deliberate — the window
# is a trust declared by the administrator, bounded in time, and every exception
# stays revocable from the TRAINING IRIS case.
TRAINING_MAX_LEVEL = int(os.environ.get("TRAINING_MAX_LEVEL", "15"))

# --- UEBA (behavioural analysis of the LOW/MEDIUM alerts) -------------------
#
# The third reduction stage, between the VT filter and the LLM (see ueba.py). It
# builds a baseline of normal behaviour per machine and per account, scores the
# RARITY of what happens in bits of information, and promotes the best-scoring
# concentrations to incident seeds. Goal: see the quiet intrusion that only emits
# level 3-11, without sending the noise to the LLM.
UEBA_ENABLED = os.environ.get("UEBA_ENABLED", "true").lower() == "true"

# Maturity of a profile. A scope that is too young is NOT scored: on day one
# everything in it is unseen — scoring would send the whole estate to the LLM. We
# observe first, we judge afterwards. Same philosophy as training mode, and the
# two combine well: the training window seeds the baseline for free.
UEBA_MATURITY_DAYS = int(os.environ.get("UEBA_MATURITY_DAYS", "7"))
UEBA_MATURITY_MIN_OBS = int(os.environ.get("UEBA_MATURITY_MIN_OBS", "200"))

# Bits given to a value NEVER seen in a mature profile. 12 bits = "one chance in
# 4096", the order of magnitude of a genuinely novel event.
UEBA_FIRSTSEEN_BITS = float(os.environ.get("UEBA_FIRSTSEEN_BITS", "12"))

# Number of hosts from which a value unseen HERE is judged mundane ELSEWHERE
# (admin rollout, update, business tool): its score is then crushed. The module's
# main anti-false-positive — without it, every new binary pushed onto the estate
# would open one incident per machine.
UEBA_FLEET_COMMON = int(os.environ.get("UEBA_FLEET_COMMON", "3"))

# Number of DISTINCT days beyond which a value is a habit and stops being
# scored. In days and not in occurrences: 500 executions in a single day is an
# incident, 5 executions over 5 days is a routine.
UEBA_DAYS_USUAL = int(os.environ.get("UEBA_DAYS_USUAL", "5"))

# CARDINALITY guardrail. A trait where nearly every observation brings a new
# value (timestamped paths, rotating LVM archives, GUIDs, session identifiers) is
# unseen by construction: "never seen" means nothing there, and it saturates the
# score permanently. Measured at go-live: the LVM archives of the Proxmox host
# alone gave a 1434-point signal, forty times the floor.
#
# We judge on the RATIO of distinct values to observations rather than on a list
# of patterns: no blacklist anticipates what an estate produces, the statistic
# corrects itself. Below MIN_OBS we do not conclude (we do not exclude a trait
# for lack of hindsight).
#
# The 0.25 threshold is not picked by eye: measured on the real estate, the
# pathological trait (LVM archives) is at 0.481 and the next one at 0.056 — an
# order of magnitude apart. 0.25 falls in the middle of the gap, hence far from
# both.
UEBA_CARDINALITY_MAX = float(os.environ.get("UEBA_CARDINALITY_MAX", "0.25"))
UEBA_CARDINALITY_MIN_OBS = int(os.environ.get("UEBA_CARDINALITY_MIN_OBS", "200"))

# Rarity floor: below it the trait is not kept as a pattern. Avoids stacking
# tenths of a bit that would end up crossing the threshold without a single
# element being abnormal.
UEBA_BITS_MIN_RARITY = float(os.environ.get("UEBA_BITS_MIN_RARITY", "4"))

# Saturation caps. Without them, a single value repeated a thousand times
# crushes everything else and the score stops describing the incident.
UEBA_CAP_TRAIT = float(os.environ.get("UEBA_CAP_TRAIT", "14"))
UEBA_CAP_ALERT = float(os.environ.get("UEBA_CAP_ALERT", "20"))

# Window grouping the low alerts of one agent into a "signal". Wider than
# CORRELATION_GAP_MINUTES: a quiet intrusion is slow, and here we are not looking
# for nameable common ground but for a CONCENTRATION.
UEBA_WINDOW_MINUTES = int(os.environ.get("UEBA_WINDOW_MINUTES", "60"))

# Maximum total duration of a signal. The chaining is step by step: without this
# cap, a host emitting one alert every 50 minutes glues its whole day into a
# single signal — the score swells by accumulation rather than by anomaly. The
# equivalent of MAX_INCIDENT_HOURS for correlation.
UEBA_SIGNAL_MAX_HOURS = int(os.environ.get("UEBA_SIGNAL_MAX_HOURS", "6"))

# MITRE chain. A plain "3 distinct tactics" mostly surfaces Discovery x3 (an
# admin inventorying their machine): the tactics are therefore WEIGHTED
# (credential-access = 5, discovery = 1) and a bonus is added when they PROGRESS
# along the kill chain order.
UEBA_MIN_TACTICS = int(os.environ.get("UEBA_MIN_TACTICS", "3"))
UEBA_BONUS_ORDER = float(os.environ.get("UEBA_BONUS_ORDER", "3"))

# Minimum score for a signal to be promotable. Calibrated on real data WITHOUT
# spending a token: `python -m soc_agent.ueba --simulation` records the signals
# and their scores without promoting anything.
UEBA_SCORE_FLOOR = float(os.environ.get("UEBA_SCORE_FLOOR", "35"))

# THE cost guardrail. A score threshold alone bounds nothing: the volume varies
# by a factor of ten between a quiet day and a campaign. The budget, in contrast,
# is a number we decide. A signal not promoted is not lost — it is re-evaluated
# on the next cycle, and its score will have grown if it continues.
# 20 promotions/day ~ 20 LLM triages/day added to the existing cost.
UEBA_BUDGET_PER_DAY = int(os.environ.get("UEBA_BUDGET_PER_DAY", "20"))
UEBA_BUDGET_PER_CYCLE = int(os.environ.get("UEBA_BUDGET_PER_CYCLE", "2"))

# Age beyond which a low alert is no longer a candidate for a signal: it had its
# chances, taking it back forever would grow the batch without end.
UEBA_RETENTION_HOURS = int(os.environ.get("UEBA_RETENTION_HOURS", "24"))

# Size of the observation batch per pass. The very first pass has to swallow the
# history already in database; the following ones only see the cycle's delta.
UEBA_BATCH = int(os.environ.get("UEBA_BATCH", "20000"))

# Memory of the baseline. A profile that never ages freezes the behaviour of six
# months ago: a reinstalled server would stay "normal" on its old binaries. Older
# observations are deleted and the profiles recomputed on what is left.
UEBA_MEMORY_DAYS = int(os.environ.get("UEBA_MEMORY_DAYS", "90"))

# Autonomous remediation on an incident coming from a UEBA signal.
#
# FALSE by default, deliberately. The rest of the pipeline acts without human
# validation because it starts from a level >= 12 seed — a Wazuh rule that
# already required several correlations. A UEBA incident starts from a
# statistical score whose accuracy is NOT measured yet: letting it isolate a host
# would mean handing production to an uncalibrated threshold. So the LLM returns
# its TP/FP verdict, the IRIS case is created with all the proposed actions, but
# nothing is executed as long as this flag is false.
UEBA_MITIGATE = os.environ.get("UEBA_MITIGATE", "false").lower() == "true"


# --- CTI / MISP -------------------------------------------------------------
#
# MISP holds the intelligence; the SQLite cache holds the DETECTION. The two are
# deliberately separated: the Wazuh integration judging every alert must depend
# neither on MISP's availability, nor on its latency, nor on an API quota. It
# reads a local file. If MISP goes down, detection carries on from the last known
# state — and rule 100956 flags the staleness.
MISP_URL = os.environ.get("MISP_URL", "https://127.0.0.1:8444")

# PUBLIC URL of MISP (the reverse proxy one), used only to build the links set
# in the enriched alerts. Distinct from MISP_URL, which is the client's call
# address: a link to https://127.0.0.1:8444 is only clickable from the manager
# itself, hence useless in an IRIS case or a dashboard opened from an analyst
# workstation.
#
# It is copied into the IOC cache (meta table) so the Wazuh integration knows it
# without duplicating the configuration on the manager side.
MISP_BASE_URL = os.environ.get("MISP_BASE_URL") or MISP_URL
MISP_KEY = os.environ.get("MISP_KEY", "")
MISP_VERIFY_TLS = os.environ.get("MISP_VERIFY_TLS", "false").lower() == "true"

# Location of the IOC cache produced by cti.py and read by the manager's
# custom-misp integration. The same docker volume on both sides (see
# docker-compose.yml, `cti_ioc` volume): written here, mounted read-only on
# /var/ossec/integrations/cti on the manager side.
CTI_CACHE = os.environ.get("CTI_CACHE", "/var/lib/aura-cti/ioc.db")

# Feed catalog. A file rather than environment variables: one entry carries a
# URL, a format, tags and a comment — unreadable in a .env, and it is content
# configuration, not deployment configuration.
CTI_CATALOG = os.environ.get(
    "CTI_CATALOG", str(Path(__file__).parent / "cti_feeds.yaml"))

# Depth of the MISP extraction, in the sense of its API's `last` parameter.
#
# BEWARE of what this window ACTUALLY filters: the last MODIFICATION date of the
# attribute, not the age of the intelligence. Everything a feed has just imported
# was modified today, so on the first import it filters almost nothing. Its real
# role is to avoid pulling the entire corpus over and over; the freshness of the
# intelligence is handled by CTI_IP_MAX_DAYS below.
CTI_WINDOW = os.environ.get("CTI_WINDOW", "90d")

# Maximum age, in days, of the originating EVENT for an IP to be kept. 0
# disables the filter.
#
# The only type of IOC that changes hands. An IP published as a C2 in 2015 is
# today a shared host or somebody's CDN — keeping it guarantees level 12 to 14
# alerts on perfectly legitimate traffic, signed "CIRCL". Observed on the first
# production import on 2026-08-12: 1,603 curated IPs, including addresses from
# 2015 reports.
#
# Applies ONLY to IPs: a file hash never expires (the file is the same), and a
# domain stays attached to whoever registered it.
CTI_IP_MAX_DAYS = int(os.environ.get("CTI_IP_MAX_DAYS", "365"))

# MISP attribute types kept. Everything else (files, registry keys, mutexes,
# mail addresses...) has no matching field in a Wazuh alert of this estate:
# ingesting it would swell the cache without ever matching.
CTI_TYPES_MISP = [t.strip() for t in os.environ.get(
    "CTI_TYPES_MISP",
    "ip-src,ip-dst,domain,hostname,url,md5,sha1,sha256").split(",") if t.strip()]

# Volume guardrail, applied to the MISP extraction as well as to every
# blocklist. A feed going off the rails (wrong URL, an HTML error page parsed as
# IOCs) must fail the synchronisation, not fill the cache with garbage.
CTI_MAX_IOC = int(os.environ.get("CTI_MAX_IOC", "1000000"))

# Age from which the cache is declared stale (rule 100956). 24 h: the fastest
# feeds run every 6 h, so four missed cycles. Below that we would alert on a mere
# job delay.
CTI_EXPIRY_HOURS = int(os.environ.get("CTI_EXPIRY_HOURS", "24"))


# --- The SOC's own infrastructure -------------------------------------------
#
# Defined at the end of the file: it depends on the URLs declared above.

def _host_url(url: str) -> str | None:
    """Host of a configuration URL, only when it is a literal IP.

    A DNS name is useless here: the comparison will be against the IP as it
    appears in an alert.
    """
    try:
        host = urlparse(url or "").hostname
    except ValueError:
        return None
    if not host:
        return None
    try:
        ipaddress.ip_address(host)
    except ValueError:
        return None
    return host


# IPs of the SOC's infrastructure: Wazuh manager, indexer, IRIS, Shuffle. NEVER
# an IOC, never a blocking target.
#
# The SIEM talks to every machine it monitors — it pushes its active responses,
# its agents answer it — so its IP appears as `srcip` or as a connection target
# on perfectly normal alerts. Published as an indicator it dirties the threat
# intel; taken at face value by an analyst or a blocking automation, it cuts the
# SOC off from its own estate. Observed on case #207: the manager's IP appeared
# there as an "internal target — /dev/tcp connection", next to the real rootkit.
#
# Three sources, combined:
#
#  - MITIGATE_ISOLATE_ALLOW: by definition "the manager IP as the AGENT reaches
#    it", that is, exactly the one appearing in the alerts. The most accurate of
#    the three.
#  - the soc-agent URLs: useful in a flat deployment, but in a container they
#    point at Docker service names and give nothing.
#  - SOC_INFRA_IPS, for the rest: VIP, second manager interface, third-party
#    collector.
SOC_INFRA_IPS = {
    ip for ip in (_host_url(INDEXER_URL), _host_url(IRIS_URL),
                  _host_url(SHUFFLE_URL), _host_url(WAZUH_API_URL)) if ip
} | set(MITIGATE_ISOLATE_ALLOW) | {
    ip.strip() for ip in os.environ.get("SOC_INFRA_IPS", "").split(",")
    if ip.strip()}


# --- Data retention (see retention.py, docs/RETENTION.md) -------------------
#
# On 2026-08-14, production was at 66 % disk with no policy anywhere: the indexer
# kept everything since installation, the `alerts` table grew by ~150 MB/day, and
# nothing watched the filling. These bounds are therefore EXPLICIT DEFAULTS: none
# is neutral, each throws data away, and that is the point.

# Age beyond which an alert is deleted from Postgres. The alerts of a still
# active incident are spared whatever their age (see retention.PURGE_ALERTS): an
# open case does not empty itself.
RETENTION_ALERTS_DAYS = int(os.environ.get("RETENTION_ALERTS_DAYS", "90"))

# Age beyond which a DATED index of the indexer is deleted by the ISM policy.
# Applies to the alerts as well as to the VOC series; `wazuh-voc-vulns`, an
# undated state index, is excluded by construction.
RETENTION_INDEX_DAYS = int(os.environ.get("RETENTION_INDEX_DAYS", "90"))

# Minimum age of a CVE feed update residue before deletion. In HOURS, and
# generous: that is what guarantees we do not delete the files of an update under
# way (those last minutes).
RETENTION_VD_TMP_HOURS = int(os.environ.get("RETENTION_VD_TMP_HOURS", "12"))

# The Wazuh manager's `queue` directory, as mounted in the retention container.
# It is the only Wazuh volume it touches, and in write mode — hence an explicit
# path rather than a discovery.
WAZUH_QUEUE_DIR = os.environ.get("WAZUH_QUEUE_DIR", "/wazuh-queue")

# Setting the ISM policy on every pass. To be set to false if index retention is
# managed elsewhere (in-house policy, S3 snapshots).
RETENTION_ISM_ENABLED = os.environ.get(
    "RETENTION_ISM_ENABLED", "true").lower() == "true"

# --- Threat hunting: restore index set (see hunting.py) ----------------------
#
# `wazuh-hunting-*` is NOT a routing index set. No log source writes to it, no
# branch of the ingest pipeline points at it: it is the workspace where archived
# data is PUT BACK to hunt in.
#
# It therefore deliberately lacks two of the five pieces of an index set (see
# docs/ROUTAGE.md), and that absence is the feature:
#
#  - **not read by ingestion.** Re-ingesting ten-month-old alerts would bring
#    them into correlation and triage, which would manufacture incidents — and
#    IRIS cases, and potentially remediations — on year-old facts. That is not a
#    preference, it is the only thing separating "restore to analyse" from
#    "replay last year's attack on an autonomous SOC". The exclusion is
#    structural: `routing.read_indices()` adds `-wazuh-hunting-*` as a negation,
#    so even someone putting `wazuh-*` in INDEXER_ALERT_INDICES could not let it
#    in.
#  - **not observed by routing.** Restored alerts carry their original
#    `decoder.name`; seen from `routing.observed_sources()`, they would look like
#    a source that stopped landing in its index — hence a ROUTING DRIFT, with the
#    IRIS alert that goes with it. Same exclusion.
#
# It does keep the template (the same mapping as the live alerts, otherwise every
# field would be `text` and no aggregation would be possible), an index pattern
# for Discover, and a retention — its own, shorter: this is workspace, not
# preservation.
HUNTING_INDEX_BASE = os.environ.get("HUNTING_INDEX_BASE", "wazuh-hunting")

# Retention of the hunting indices, in days, through a DEDICATED ISM policy
# (`aura-hunting`). Shorter than the live alerts one: what is here is a COPY of
# an archive that itself lives twelve months. Losing it loses nothing, and
# leaving restores lying around is the simplest way to fill the SOC disk.
HUNTING_RETENTION_DAYS = int(os.environ.get("HUNTING_RETENTION_DAYS", "30"))

# Restore guardrails. They exist because this space is reachable from the MCP
# server, hence by an AI agent: "restore everything so I can look" must be
# refused by the code, not discouraged by an instruction. A full disk stops the
# WHOLE SOC (see docs/RETENTION.md).
HUNTING_MAX_DOCS = int(os.environ.get("HUNTING_MAX_DOCS", "2000000"))
HUNTING_MAX_INDICES = int(os.environ.get("HUNTING_MAX_INDICES", "10"))
HUNTING_MAX_BYTES = int(float(
    os.environ.get("HUNTING_MAX_GB", "10")) * 1073741824)

# Size of the `_bulk` batches of the re-injection. 2,000 alert documents make a
# ~6 MB request: beyond that the indexer rejects or pressures its heap without
# the re-injection going any faster.
HUNTING_BULK_SIZE = int(os.environ.get("HUNTING_BULK_SIZE", "2000"))

# --- Cold archiving to S3 (see archive.py, docs/ARCHIVAGE.md) ---------------
#
# The retention above DELETES at 90 days. A SOC must be able to answer later than
# that: a judicial request, an audit, an intrusion discovered six months after it
# began. Archiving is the copy that survives the purge — not a backup of the
# indexer, a SELF-CONTAINED copy, readable without it.
#
# Three principles carried by these settings, each against a way of losing the
# data:
#
#  - one object per (index set x month), in compressed NDJSON. No OpenSearch
#    snapshot: a snapshot only reads back with a cluster of a compatible version,
#    and its tree is opaque. An archive must stand alone.
#  - CLIENT-SIDE encryption before the upload, with a key the SOC holds entirely:
#    it encrypts and decrypts its own archives. The provider only ever sees
#    opaque bytes, which is the point; on the other hand whoever gets root on
#    this host gets the key, hence the whole history. A deliberate operational
#    choice (fully automatic drill, restore with no manual step) — see the
#    threat-model section of docs/ARCHIVAGE.md.
#  - nothing is declared archived without the object having been read back on the
#    S3 side. The marker lives in Postgres, never in the remote system — the same
#    lesson as the IRIS Evidence pieces, which were re-posted in a loop because
#    the list of "already set" ones was asked of IRIS and fell back to empty on
#    failure.
ARCHIVING_ENABLED = os.environ.get("ARCHIVING_ENABLED", "false").lower() == "true"


def _archive_required(name: str) -> str:
    """Requis SEULEMENT si l'archivage est actif.

    `config` is imported by the eleven containers of the pipeline: an
    unconditional `_required` would stop them all from starting over a feature
    nobody enabled. Once ARCHIVING_ENABLED=true, however, a missing credential
    MUST stop the startup — archiving that fails silently is worse than no
    archiving: it makes people believe the copy exists.
    """
    return _required(name) if ARCHIVING_ENABLED else os.environ.get(name, "")


# Version of the archive FORMAT, carried by the prefix of the S3 keys. The day
# the codec, the projection or the manifest structure change, `v2/` coexists with
# `v1/` unambiguously and a reading tool knows what it is dealing with without
# guessing. Do not increment it for a setting change.
ARCHIVE_FORMAT_VERSION = os.environ.get("ARCHIVE_FORMAT_VERSION", "v1")

# Backblaze B2 S3 endpoint. The region is part of the host name; picking an EU
# region (eu-central-003, Amsterdam) avoids a transfer outside the EU to
# document. That does NOT put the data out of reach of the CLOUD Act — Backblaze
# is a US company — client-side encryption is what takes care of that.
ARCHIVE_S3_ENDPOINT = os.environ.get(
    "ARCHIVE_S3_ENDPOINT", "https://s3.eu-central-003.backblazeb2.com")
ARCHIVE_S3_REGION = os.environ.get("ARCHIVE_S3_REGION", "eu-central-003")
ARCHIVE_S3_BUCKET = _archive_required("ARCHIVE_S3_BUCKET")
ARCHIVE_S3_KEY_ID = _archive_required("ARCHIVE_S3_KEY_ID")
ARCHIVE_S3_APP_KEY = _archive_required("ARCHIVE_S3_APP_KEY")

# Optional root prefix, if the bucket is shared with something else. Empty by
# default: a bucket DEDICATED to archiving is the right setting, it allows
# scoping the application key to that bucket alone.
ARCHIVE_S3_PREFIX = os.environ.get("ARCHIVE_S3_PREFIX", "").strip("/")

# `age` key file held by the SOC, as seen from the container. It carries the
# COMPLETE key: the module encrypts with it and decrypts with it.
#
# A single secret for both directions, and that is intended: the restore drill
# can go all the way to decryption on its own (hence prove the READABILITY of an
# archive, not only its integrity), and restoring a month requires no key
# mounting by hand.
#
# What it costs, to know rather than to discover: this file is the only thing
# between an attacker with root on this host and the twelve months of archives.
# Protecting it (0400, root, outside any shared volume) is part of the design,
# not of good manners.
#
# The file is mounted READ-ONLY from a DIRECTORY of the host
# (ARCHIVE_KEY_DIR_HOST). Mounting the file directly exposes the house trap: if
# the source path does not exist, docker creates a DIRECTORY in its place and the
# container breaks at startup with no clear message (see SSH_KEY_HOST).
ARCHIVE_AGE_KEYFILE = os.environ.get(
    "ARCHIVE_AGE_KEYFILE", "/run/secrets/aura-archive-age.key")

# ADDITIONAL recipients, as comma-separated age public keys. Optional, and
# useful for one thing only: a backup key whose private half sleeps offline, in a
# safe. Every archive then becomes decryptable by the SOC *or* by that key — the
# SOC can lose its own without losing the history.
ARCHIVE_AGE_RECIPIENTS_EXTRA = [
    r.strip() for r in
    os.environ.get("ARCHIVE_AGE_RECIPIENTS_EXTRA", "").split(",") if r.strip()]

if ARCHIVING_ENABLED:
    _kf = Path(ARCHIVE_AGE_KEYFILE)
    if not _kf.is_file():
        sys.exit(
            f"ARCHIVE_AGE_KEYFILE not found: {ARCHIVE_AGE_KEYFILE}. Refusing to "
            "archive in clear. Generate the key on the host with "
            "`age-keygen -o /etc/aura/keys/aura-archive-age.key` then check that "
            "ARCHIVE_KEY_DIR_HOST is mounted (see docs/ARCHIVAGE.md).")
    try:
        _content = _kf.read_text(encoding="utf-8", errors="replace")
    except OSError as _e:
        sys.exit(f"ARCHIVE_AGE_KEYFILE unreadable ({ARCHIVE_AGE_KEYFILE}): {_e}")
    if "AGE-SECRET-KEY-1" not in _content:
        sys.exit(
            f"ARCHIVE_AGE_KEYFILE ({ARCHIVE_AGE_KEYFILE}) contains no age key "
            "(\"AGE-SECRET-KEY-1...\"). Do not put a PUBLIC key there: this file "
            "must allow decrypting, otherwise the restore drill can prove "
            "nothing.")
    # A key readable by everyone is no longer a secret. We say so without
    # blocking: it is a permission on the host, not a configuration error, and
    # refusing to start would lose archiving over a chmod.
    try:
        _mode = _kf.stat().st_mode & 0o077
        if _mode:
            print(f"ARCHIVING WARNING: {ARCHIVE_AGE_KEYFILE} is readable beyond "
                  f"its owner (mode ...{_mode:03o}). This key decrypts EVERY "
                  "archive: `chmod 400` on the host.", file=sys.stderr)
    except OSError:
        pass
    if not ARCHIVE_AGE_RECIPIENTS_EXTRA:
        print("ARCHIVING WARNING: no backup key "
              "(ARCHIVE_AGE_RECIPIENTS_EXTRA empty). Losing "
              f"{ARCHIVE_AGE_KEYFILE} would make every archive PERMANENTLY "
              "unreadable — nobody recovers them, neither Backblaze nor us. Back "
              "this file up offline, or add a backup key.", file=sys.stderr)
    _bad = [r for r in ARCHIVE_AGE_RECIPIENTS_EXTRA
                if not (r.startswith("age1") and len(r) >= 58)]
    if _bad:
        sys.exit(f"ARCHIVE_AGE_RECIPIENTS_EXTRA: invalid value(s) {_bad}. "
                 "Expected an age PUBLIC key (\"age1...\", 62 characters), not a "
                 "file path nor a private key.")

# Object Lock (WORM). This is what distinguishes archiving from a backup: it
# allows stating in front of an auditor that the object could not be modified.
#
# It only activates on a bucket created with Object Lock — the property does not
# apply retroactively to an existing bucket. In COMPLIANCE mode NO deletion is
# possible before the deadline, including by the account owner and including on a
# mistake: the twelve-month bill is due. Hence false by default, to be switched
# knowingly.
ARCHIVE_OBJECT_LOCK = os.environ.get(
    "ARCHIVE_OBJECT_LOCK", "false").lower() == "true"
ARCHIVE_OBJECT_LOCK_MODE = os.environ.get(
    "ARCHIVE_OBJECT_LOCK_MODE", "COMPLIANCE").upper()
ARCHIVE_OBJECT_LOCK_DAYS = int(
    os.environ.get("ARCHIVE_OBJECT_LOCK_DAYS", "365"))

if ARCHIVING_ENABLED and ARCHIVE_OBJECT_LOCK_MODE not in ("COMPLIANCE", "GOVERNANCE"):
    sys.exit("ARCHIVE_OBJECT_LOCK_MODE must be COMPLIANCE or GOVERNANCE, not "
             f"\"{ARCHIVE_OBJECT_LOCK_MODE}\".")

# Candidate index patterns. `wazuh-*` DELIBERATELY broad: the house trap is the
# list to keep up to date that gets forgotten (three times for
# INDEXER_ALERT_INDICES, see docs/ROUTAGE.md). An index set created tomorrow by
# routing.py must be archived without anyone thinking about it.
#
# What actually bounds it is the shape of the name: only DAY-DATED indices
# (`-YYYY.MM.DD`) are archived. Excluded by construction, with no list:
# `wazuh-voc-vulns` (an undated state index, it carries the MTTR),
# `wazuh-monitoring-*` and `wazuh-statistics-*` (dated to the week, Wazuh's
# internal telemetry). The month is read from the index NAME, never from an
# `@timestamp`: no time zone in the equation.
ARCHIVE_INDEX_PATTERNS = os.environ.get("ARCHIVE_INDEX_PATTERNS", "wazuh-*")

# Additional exclusions, as glob patterns on the full index name.
#
# The threat hunting space is ALWAYS in there, whatever is put in the variable:
# it holds copies restored from the archives, re-archiving them would mean
# archiving an archive — and under Object Lock, paying twice for the same data
# for twelve months. The hunting index names are already not day-dated, so they
# are excluded by shape; this line is the second barrier, the one that holds even
# if the naming changes.
ARCHIVE_INDEX_EXCLUDED = [
    m.strip() for m in os.environ.get("ARCHIVE_INDEX_EXCLUDED", "").split(",")
    if m.strip()] + [f"{HUNTING_INDEX_BASE}-*"]

# Fields removed from `_source` before writing (OpenSearch patterns, `a.b.*`
# accepted). EMPTY by default, and that is a choice: a truncated archive does not
# repair itself, and the saving would be a few gigabytes a year — the order of
# magnitude of the price of a coffee. Only to be filled in if volume becomes a
# real problem, and to be documented in the manifest (which `excluded_fields`
# does).
ARCHIVE_EXCLUDED_FIELDS = [
    c.strip() for c in os.environ.get("ARCHIVE_EXCLUDED_FIELDS", "").split(",")
    if c.strip()]

# zstd level. 19 is the best trade-off on alert JSON (~20-30x); beyond it
# (`--ultra`) the gain is marginal and the memory blows up.
ARCHIVE_ZSTD_LEVEL = int(os.environ.get("ARCHIVE_ZSTD_LEVEL", "19"))

# Grace delay after the end of the month before archiving it. This is not
# decorative caution: the catch-up of late-indexed alerts (see INGEST_SWEEP_*)
# and an index created across midnight can still write into the elapsed month.
# Archiving too early freezes an incomplete copy.
ARCHIVE_DELAY_DAYS = int(os.environ.get("ARCHIVE_DELAY_DAYS", "2"))

# Archive retention, in months. Serves as a reference for the manifest and the
# gap check: the deletion itself belongs to the bucket's LIFECYCLE RULE, not to
# this code. A cron that dies must not grow the bill forever, and the code is not
# allowed to delete (the production application key does not carry
# `deleteFiles`).
ARCHIVE_RETENTION_MONTHS = int(os.environ.get("ARCHIVE_RETENTION_MONTHS", "12"))

# Safety margin between archiving and the ISM purge, in days. An index entering
# this margin without a confirmed archive is REMOVED from the ISM policy by
# `retention.py`: it stops being a candidate for deletion until its copy exists.
# That is the only mechanism actually preventing the loss — suspending the
# setting of the policy would not be enough, it is already attached to the
# indices and would keep deleting them.
ARCHIVE_MARGIN_DAYS = int(os.environ.get("ARCHIVE_MARGIN_DAYS", "7"))

# Page size of the export (scroll). 5,000 Wazuh alert documents weigh ~15 MB in
# JSON: going much higher grows the indexer's response without speeding the
# export up.
ARCHIVE_BATCH_SIZE = int(os.environ.get("ARCHIVE_BATCH_SIZE", "5000"))

# Restore drill. On every pass, the N archives verified least recently are
# downloaded again, their SHA-256 recomputed, then DECRYPTED and recounted
# against their manifest. An untested archive is a belief, not a copy.
#
# The drill goes as far as decryption because the SOC holds its key: it therefore
# proves READABILITY, not only the integrity of the storage. That is the main
# operational benefit of the symmetric key choice.
#
# FULL=false stops at the SHA-256 of the object. Useful transiently (key
# momentarily absent) so as not to declare failed what we simply could not
# read.
ARCHIVE_DRILL_BATCH = int(os.environ.get("ARCHIVE_DRILL_BATCH", "3"))
ARCHIVE_DRILL_DAYS = int(os.environ.get("ARCHIVE_DRILL_DAYS", "90"))
ARCHIVE_DRILL_FULL = os.environ.get(
    "ARCHIVE_DRILL_FULL", "true").lower() == "true"

# Working directory. The archive is written there ALREADY ENCRYPTED — the
# plaintext never touches the disk, it only crosses pipes. Plan for room: the
# module refuses to start an export if it has nothing to write it with, because a
# full disk stops the whole SOC (see docs/RETENTION.md).
ARCHIVE_TMP_DIR = os.environ.get("ARCHIVE_TMP_DIR", "/tmp")

# --- Archive dashboard (see archive_metrics.py, docs/ARCHIVAGE.md) ---------
#
# The catalog (`archives_s3`) is exported to this fixed-name index (no date
# suffix, one document per (index set, month)) so it can be read in a Wazuh
# dashboard next to the alerts. No `-*` date rotation: unlike alerts, an
# archive doesn't happen every day, and there is nothing to purge — a state
# index, same convention as `wazuh-voc-vulns`. Its very name keeps it out of
# `archive.py`'s own scan (`_DATE_INDEX` requires a `-YYYY.MM.DD` suffix).
ARCHIVE_METRICS_INDEX = os.environ.get(
    "ARCHIVE_METRICS_INDEX", "wazuh-archive-catalog")

# Backblaze B2's published rate (see docs/ARCHIVAGE.md), USD per GB per month.
# An estimate, like `LLM_COST_USD_PER_MTOKEN_*`: it prices the ENCRYPTED
# object actually stored, not the plaintext, and says nothing about egress
# (free up to 3x the stored volume, so irrelevant to a monthly figure).
ARCHIVE_S3_COST_USD_PER_GB_MONTH = float(
    os.environ.get("ARCHIVE_S3_COST_USD_PER_GB_MONTH", "0.00695"))

# --- Disk guardrail (see watchdog.py) ---------------------------------------
#
# Six gigabytes a day were going without anything saying so. A SOC that does not
# watch its own disk stops silently: indexer read-only, Postgres refusing to
# write, no alert entering any more.
DISK_MONITORED = os.environ.get("DISK_MONITORED", "/")
# Occupancy thresholds, as percentages. `alert` opens a Medium IRIS alert,
# `critical` raises it to High — same channel, same life cycle.
DISK_THRESHOLD_ALERT = int(os.environ.get("DISK_THRESHOLD_ALERT", "80"))
DISK_THRESHOLD_CRITICAL = int(os.environ.get("DISK_THRESHOLD_CRITICAL", "90"))
